# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Deploy App Service (Chai Chatbot)

on:
  push:
    branches: [ deployment ]   # <-- change branch if needed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build frontend
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        run: |
          cd frontend
          echo "VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}" >> .env
          echo "VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}" >> .env
          npm ci
          npm run build
          cd ..
          rm -rf backend/static
          mkdir -p backend/static
          cp -R frontend/dist/* backend/static/

      # Install backend deps
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
          cd ..

      # Zip only backend folder
      - name: Create deployment package
        run: |
          cd backend
          zip -r ../backend.zip .
          cd ..

      # Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chai-corner-chatbot"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "backend.zip"
