# Deploy App Service (Chai Chatbot) - self-contained ZIP (no Oryx)
name: Deploy App Service (Chai Chatbot)

on:
  push:
    branches: [ deployment ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Build frontend ----------
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd frontend
          echo "VITE_PAYPAL_CLIENT_ID=${{ secrets.VITE_PAYPAL_CLIENT_ID }}" >> .env
          echo "VITE_STRIPE_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}" >> .env
          npm ci
          npm run build
          cd ..
          rm -rf backend/static
          mkdir -p backend/static
          cp -R frontend/dist/* backend/static/

      # ---------- Vendor Python deps into the artifact ----------
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Vendor backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target .python_packages/lib/site-packages
          cd ..

      - name: Sanity check vendored packages
        run: |
          ls -1 backend/.python_packages/lib/site-packages | grep -E 'fastapi|uvicorn|gunicorn' || true

      # ---------- Create deployable ZIP (includes .python_packages) ----------
      - name: Create deployment package
        run: |
          cd backend
          zip -r ../app.zip . -x "**/.git/**" "**/__pycache__/**"
          cd ..

      # ---------- Deploy ----------
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chai-corner-chatbot"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "app.zip"
